<footer>
  <div class="footer-wrapper">
    <div class="container">
      <div class="inside-container">
        <div class="row">
          <div class="col-sm-4 widget-col-1">
            <div id="text-2" class="footer-widget widget widget_text">
              <h4 class="widget-title">Get in touch with us</h4>
              <div class="textwidget">
                <p>Tel: (65) 6702 0708<br/>
                  Fax: (65) 6358 4527</p>
                <p>Email: <a href="mailto:info@petcubes.com.sg">info@petcubes.com.sg</a></p>
              </div>
            </div>
          </div>
          <div class="col-sm-4 widget-col-2">
            <div id="mc4wp_form_widget-2" class="footer-widget widget widget_mc4wp_form_widget">
              <h4 class="widget-title">Subscribe for the latest news</h4>
              <form id="mc4wp-form-1" class="mc4wp-form mc4wp-form-165" method="post" data-id="165" data-name="" >
                <div class="mc4wp-form-fields">
                  <div class="petcubes-subcribe-form">
                    <div class="form-inline">
                      <div class="form-group">
                        <input type="email" class="form-control petcubes-subscribe-field" name="EMAIL" placeholder="Your email address" required />
                        <button type="submit" class="petcubes-subscribe-btn"><i class="fa fa-angle-right" aria-hidden="true"></i></button>
                      </div>
                    </div>
                  </div>
                  <div style="display: none;">
                    <input type="text" name="_mc4wp_honeypot" value="" tabindex="-1" autocomplete="off" />
                  </div>
                  <input type="hidden" name="_mc4wp_timestamp" value="1479887070" />
                  <input type="hidden" name="_mc4wp_form_id" value="165" />
                  <input type="hidden" name="_mc4wp_form_element_id" value="mc4wp-form-1" />
                </div>
                <div class="mc4wp-response"></div>
              </form>
              <!-- / MailChimp for WordPress Plugin --></div>
          </div>
          <div class="col-sm-4 widget-col-3">
            <div id="text-3" class="footer-widget widget widget_text">
              <h4 class="widget-title">Follow us</h4>
              <div class="textwidget"><a href="#" class="social-icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="#" class="social-icon youtube"><i class="fa fa-youtube-play" aria-hidden="true"></i></a><a href="#" class="social-icon skype"><i class="fa fa-skype" aria-hidden="true"></i></a></div>
            </div>
          </div>
        </div>
        <!--<p>&copy;  </p>--> 
      </div>
    </div>
    <!-- /container --> 
  </div>
</footer>
<script type='text/javascript' src='<?php echo $this->getSkinUrl('js/jquery.js') ?>'></script> 
<script type='text/javascript' src='<?php echo $this->getSkinUrl('js/javascript.js') ?>'></script>
</body>
</html>