<footer>
<?php

if (Mage::registry('current_category'))
{ ?>
<style>
.container.box_a {
    border: medium none;
    margin-top: 0;
    padding-top: 0;
}
</style>
<div class="yellow-gradient-bg">
<?php
$id=Mage::registry('current_category')->getId();
if($id==241)
{ ?>
<div class="container box_a">



  	



   




    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="<?php echo $this->getSkinUrl('images/a3.png') ?>"/>



        </div>



        <h3>cooked at 80 degrees to eliminate bacteria and parasites while retaining minerals and vitamins</h3>



   </div>
   
   <div class="col-md-2 text-center margin-bottom-10 complete">



   		<div class="a_img">



   		<img src="<?php echo $this->getSkinUrl('images/icon1.png') ?>"/>



        </div>



        <h3>formulated as whole meals with added nutrition</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="<?php echo $this->getSkinUrl('images/a4.png') ?>"/>



        </div>



        <h3>immediately packed & blast frozen to lock in freshness</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="<?php echo $this->getSkinUrl('images/a5.png') ?>"/>



        </div>



        <h3>wholesome & nutritious</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="<?php echo $this->getSkinUrl('images/a6.png') ?>"/>



        </div>



        <h3>ideal for dogs of all ages</h3>



   </div>
   <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="<?php echo $this->getSkinUrl('images/icon4.png') ?>"/>



        </div>



        <h3>helps to create a robust immune & digestive system</h3>



   </div>



  </div>
<?php
}
else if($id==242)
{ ?>
<div class="container box_a">



  	



   <div class="col-md-2 text-center margin-bottom-10 raw">



   		<div class="a_img">



   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/a1.png">



        </div>



        <h3>wholesome, nutritious meal in raw form</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/icon4.png">



        </div>



        <h3>fortified with super antioxidants</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/a5.png">



        </div>



        <h3>protein &amp; nutients in a form that dogs consume in their natural environment</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/a4.png">



        </div>



        <h3>immediately packed &amp; blast frozen to lock in freshness</h3>



   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/a3.png">



        </div>



        <h3>stored at -25 degree celsius to kill parasites</h3>





   </div>



   



    <div class="col-md-2 text-center margin-bottom-10">



   		<div class="a_img">



   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/a6.png">



        </div>



        <h3>ideal for dogs of all ages</h3>



   </div>



  </div>
<?php
	
}
else if($id==259)
{ ?>

<div class="container box_a">



  	



   <div class="col-md-12 text-center margin-bottom-10 premium">



   		<div class="a_img">


   		<img src="http://petcubes.exxelnet.sg/skin/frontend/athlete/default/images/a1.png">



        </div>



        <h3>Great Nutritious Addition To Regular Meals</h3>



   </div>
  </div>
<?php
}
?>

</div>
<?php
	
  // Category Name
  //echo Mage::registry('current_category')->getName();

  // Category ID
 //$id=Mage::registry('current_category')->getId();
}
?>

  <div class="footer-wrapper">

    <div class="container">

      <div class="inside-container">

        <div class="row">

          <div class="col-sm-4 widget-col-2">

            <div id="text-2" class="footer-widget widget widget_text">

              <h4 class="widget-title text-left">Get in touch with us</h4>

              <div class="textwidget">

<ul>
<li style="text-align: left;">Tel: (65) 6384 2441</li>
<li style="text-align: left;">Whatsapp: (65) 9737 8573</li>
<li style="text-align: left;">Email: <a href="mailto:info@petcubes.com.sg">info@petcubes.com.sg</a></li>
</ul>

              </div>

            </div>
           
           <!-- <div class="col-sm-4 widget-col-3">
            <div class="footer-widget widget widget_text">
            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'news'; ?>" style="text-decoration:none !important" class="blog-footer"><h4 class="widget-title text-left">Blogs</h4></a>
            </div>
            </div>-->

          </div>

 <div class="col-sm-4 widget-col-2">
         

            <div id="mc4wp_form_widget-2" class="footer-widget widget widget_mc4wp_form_widget">

              <h4 class="widget-title">Subscribe for the latest news</h4>

              

                                           <?php

echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-three')->toHtml(); 

?>

              <!-- / MailChimp for WordPress Plugin --></div>

          </div>
          

          <div class="col-sm-4 widget-col-3" style="text-align:center !important;">

            <div id="text-3" class="footer-widget widget widget_text">

              <h4 class="widget-title">Follow us</h4>

             <!-- <div class="textwidget"><a href="#" class="social-icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="https://www.facebook.com/petcubes/" class="social-icon youtube"><i class="fa fa-youtube-play" aria-hidden="true"></i></a><a href="#" class="social-icon skype"><i class="fa fa-skype" aria-hidden="true"></i></a></div>-->
             <div class="textwidget">
            <a href="https://www.facebook.com/petcubes/" class="social-icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
<!--<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'news'; ?>" class="social-icon blogic"><img src="<?php echo $this->getSkinUrl('images/blok-ic.png') ?>"/></a>-->
<a href="https://www.instagram.com/petcubes/?hl=en" class="social-icon facebook"><i class="fa fa-instagram" aria-hidden="true"></i></a>
</div>
            </div>

          </div>
</div>
        </div>

        <!--<p>&copy;  </p>--> 

      </div>

    </div>

    <!-- /container --> 

  </div>

</footer>


<script type='text/javascript' src='<?php echo $this->getSkinUrl('js/jquery.js') ?><?php echo $this->getSkinUrl('js/jquery.js') ?>'></script> 

<script type='text/javascript' src='<?php echo $this->getSkinUrl('js/javascript.js') ?>'></script>
<script>(function(d, s, id) {

		var js, fjs = d.getElementsByTagName(s)[0];

		if (d.getElementById(id))

			return;

		js = d.createElement(s);

		js.id = id;

		js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=195555774072";

		fjs.parentNode.insertBefore(js, fjs);

	}(document, 'script', 'facebook-jssdk'));</script>
    
    
	<!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
var __lc = {};
__lc.license = 6461861;

(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<!-- End of LiveChat code -->


	

  
  

</body>

</html>