<div class="footer-subscribe">
	<!--<div class="title"><?php echo $this->__('SIGN UP TODAY!') ?></div>-->
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="footer-newsletter-validate-detail">
		<p><?php //echo $this->__('<b>Information on Pet, Nutrition and More</b>') ?></p>
		<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button">
			<span><span><?php //echo $this->__('Subscribe') ?></span></span></button>
		<div class="input-box">
		<input type="text" name="email" id="footer-newsletter" placeholder="email address"
		       title="<?php echo $this->__('Sign up for our newsletter') ?>"
		       class="input-text required-entry validate-email"/>
		</div>
		<div class="clear"></div>
	</form>
	<script type="text/javascript">
		//<![CDATA[
		var newsletterSubscriberFormDetail = new VarienForm('footer-newsletter-validate-detail');
		//]]>
	</script>
</div>